source 'https://ruby.taobao.org'
#ruby '2.2.3'
gem 'rails', '4.2.7'
gem 'activerecord-jdbcsqlite3-adapter'
gem 'activerecord-oracle_enhanced-adapter', '~> 1.6.0'
#gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
#gem 'coffee-rails', '~> 4.0.0'
#gem 'therubyrhino'
#gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',                              group: :doc
#gem 'bootstrap-sass'
gem 'devise'
gem 'devise_ldap_authenticatable','0.8.1'
gem 'haml-rails'
gem 'high_voltage'
gem 'simple_form'
gem 'puma'
gem 'axlsx', '2.1.0.pre'
gem 'rubyzip', '~> 1.1.0'
gem 'axlsx_rails'
gem 'uuid'
gem 'kaminari'

group :development do
  gem 'better_errors'
  gem 'html2haml'
  gem 'rails_layout'
  gem 'pry-rails'
end
